### ISSUE TITLE
Evaluate -Toggle logic

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/all_in_oil#23]
# Add toggle logic to Evaluations

## Value statement
As a **user**
I want **to see all my evaluation as a list of cards wit small thumbnails** but when clicking on them i want to be able to see all the information a save for that particular evaluation
----
## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ] display evaluation as a card just with name and small image of the label
 - [ ]   on click on  that "card" the evaluation needs to open and display the whole content that was previously saved by the user
- [ ] the "card needs to have toggle logic, meaning, it needs to be clickable for open and close

---

## Tasks
- [ ] add state with toggle logic
- [ ] change the size of the image when the open/close changes
- [ ] Test in mobile and desktop view

## Size
Medium
