### ISSUE TITLE
Guide-how to taste your olive oil

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/all_in_oil#24]
# Guide-how to taste your olive oil

## Value statement
As a **user**
I want **learn the process of tasting the olive oil** so i need to have so simple, basic text that follows the tasting steps. And  the according images for the specific step.
----
## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
- [ ] 3 basic steps to follow the evaluation of the oil
- [ ]  the images need to look artistic but still be recognisable for the reader/user
---

## Tasks
- [ ] create a separate page for the guide
- [ ] add all the necessary paragraphs and images
- [ ] Test in mobile and desktop view

## Size
small
