### ISSUE TITLE
Implement Search bar

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/all_in_oil#25]
# Implement Search bar

## Value statement

As a **user**
I want **to be able to search trough the evaluation list** so i can have faster excess to the  informations I've gathered.
----
## Description (Text, Scribble, Wireframe, Design)

---

## Acceptance criteria
 - [ ] search field above the evaluation list 
 - [ ]  when starting to type the search has to be synchronous
 - [ ]  the search must not be case sensitive 
- [ ] the cards  with matched information shout appear below

---

## Tasks
- [ ] create input filed with search icon above the evaluation list 
- [ ]create a non case sensitive search
- [ ] Test in mobile and desktop view

## Size
Medium
