### ISSUE TITLE
Add delete option

### ISSUE THREAD

**Issue by bartolivana** [bartolivana/all_in_oil#26]
# Add delete option 
### As a **user** I want **to be able to remove evaluation** in order to create a new one or just to keep my list tidy. 
---- 

## Description (Text, Scribble, Wireframe, Design)

 --- 

## Acceptance criteria 

- [ ] delete button on top of each evaluation card 
- [ ]on click an alert window opens to approve the removal of the evaluation 
- [ ] delete button should be a small trash can, no text needed, except in the alert window 
--- 

## Tasks 
- [ ] create delete icon in the evaluation list on top of each evaluation card 
- [ ] and add the corresponding logic to the created icon/button - [ ] create delete alert or pop up window to approve the delete function. 

## Size Medium
